#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nvidia-settings
Version  : 430.14
Release  : 1
URL      : https://github.com/NVIDIA/nvidia-settings/archive/430.14.tar.gz
Source0  : https://github.com/NVIDIA/nvidia-settings/archive/430.14.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: nvidia-settings-bin = %{version}-%{release}
Requires: nvidia-settings-data = %{version}-%{release}
Requires: nvidia-settings-man = %{version}-%{release}
Requires: nvidia-settings-plugins = %{version}-%{release}
BuildRequires : dbus-dev
BuildRequires : gtk+-dev
BuildRequires : gtk3-dev
BuildRequires : libXv-dev
BuildRequires : libvdpau-dev
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(x11)

%description
nvidia-settings: A tool for configuring the NVIDIA X driver on Unix and Linux systems

%package bin
Summary: bin components for the nvidia-settings package.
Group: Binaries
Requires: nvidia-settings-data = %{version}-%{release}

%description bin
bin components for the nvidia-settings package.


%package data
Summary: data components for the nvidia-settings package.
Group: Data

%description data
data components for the nvidia-settings package.


%package man
Summary: man components for the nvidia-settings package.
Group: Default

%description man
man components for the nvidia-settings package.


%package plugins
Summary: plugins components for the nvidia-settings package.
Group: Default

%description plugins
plugins components for the nvidia-settings package.


%prep
%setup -q -n nvidia-settings-430.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559233284
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1559233284
rm -rf %{buildroot}
%make_install PREFIX=/usr
## install_append content
install -D -m644 doc/nvidia-settings.desktop "%{buildroot}/usr/share/applications/nvidia-settings.desktop"
install -D -m644 doc/nvidia-settings.png "%{buildroot}/usr/share/pixmaps/nvidia-settings.png"
sed -e 's:__UTILS_PATH__:/usr/bin:' -e 's:__PIXMAP_PATH__:/usr/share/pixmaps:' -i "%{buildroot}/usr/share/applications/nvidia-settings.desktop"
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nvidia-settings

%files data
%defattr(-,root,root,-)
/usr/share/applications/nvidia-settings.desktop
/usr/share/pixmaps/nvidia-settings.png

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/nvidia-settings.1.gz

%files plugins
%defattr(-,root,root,-)
/usr/lib/libnvidia-gtk2.so.430.14
/usr/lib/libnvidia-gtk3.so.430.14
